version: '2'

services:
  api:
    restart: always
    build: ./server
    command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    environment:
      - ENV_CONFIG=production
    env_file:
      - db.env
    links:
      - postgres
  postgres:
    restart: always
    image: "postgres:latest"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data:Z
  client:
    build: ./client
    ports:
      - "9999:80"
    command: "nginx -g 'daemon off;'"
    links:
      - api
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    # volumes_from:
      # - api
    links:
      - api

volumes:
  data-postgres:
