version: '2'

services:
  web:
    build: .
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/application
    links:
      - mongo
      - postgres
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo:3.0.2
    volumes:
      - data-mongo:/data/db
  postgres:
    image: "postgres:9.4"
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
  data-mongo:
