version: '2'

services:
  api:
    restart: always
    build: ./api
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    env_file: .env
    links:
      - postgres
  postgres:
    restart: always
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    # volumes_from:
      # - api
    links:
      - api:api

volumes:
  data-postgres:
