version: '2'

services:

  api:
    restart: always
    build: ./server
    command: /usr/local/bin/gunicorn --log-level DEBUG -w 4 -b 0.0.0.0:8001 wsgi:app
    expose:
      - "8001"
    volumes:
      - .:/api
    env_file:
      - web.env
      - db.env

  postgres:
    restart: always
    image: "postgres:latest"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data:Z

  client:
    build: ./client
    expose:
      - "8002"
    command: "nginx -g 'daemon off;'"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"

  # dclient:
  #   image: node:6.1
  #   ports:
  #     - "8888:8080"
  #   volumes:
  #   - ./client/:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: sh -c 'npm run dev'

volumes:
  data-postgres:
