"""empty message

Revision ID: 1469066eff43
Revises: d7de00159c03
Create Date: 2016-11-02 13:51:41.460027

"""

# revision identifiers, used by Alembic.
revision = '1469066eff43'
down_revision = 'd7de00159c03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    ### end Alembic commands ###
