"""empty message

Revision ID: 8b9de539bfbf
Revises: None
Create Date: 2016-11-02 11:35:12.377905

"""

# revision identifiers, used by Alembic.
revision = '8b9de539bfbf'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_num', 'exercise_id', 'workout_id', name='_exercise_set_workout_uc')
    )
    op.create_unique_constraint(None, 'exercise', ['name'])
    op.drop_constraint(u'exercise_workout_id_fkey', 'exercise', type_='foreignkey')
    op.drop_column(u'exercise', 'comment')
    op.drop_column(u'exercise', 'set_num')
    op.drop_column(u'exercise', 'reps')
    op.drop_column(u'exercise', 'workout_id')
    op.drop_column(u'exercise', 'weight')
    op.add_column(u'workout', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column(u'workout', 'workout_json')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'workout', sa.Column('workout_json', postgresql.JSON(astext_type=Text()), autoincrement=False, nullable=True))
    op.drop_column(u'workout', 'date_created')
    op.add_column(u'exercise', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'exercise', sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'exercise', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'exercise', sa.Column('set_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'exercise', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'exercise_workout_id_fkey', 'exercise', 'workout', ['workout_id'], ['id'])
    op.drop_constraint(None, 'exercise', type_='unique')
    op.drop_table('exercise_entry')
    ### end Alembic commands ###
