"""empty message

Revision ID: b67a4ab1043d
Revises: 1469066eff43
Create Date: 2016-11-10 13:51:02.422326

"""

# revision identifiers, used by Alembic.
revision = 'b67a4ab1043d'
down_revision = '1469066eff43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
