"""empty message

Revision ID: d71a22e997db
Revises: b67a4ab1043d
Create Date: 2016-11-18 12:33:44.760861

"""

# revision identifiers, used by Alembic.
revision = 'd71a22e997db'
down_revision = 'b67a4ab1043d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_proposed', sa.Date(), nullable=False),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_num', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_num', 'exercise_id', 'workout_id', name='_exercise_set_workout_uc')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_entry')
    op.drop_table('workout')
    op.drop_table('exercise')
    ### end Alembic commands ###
