export const GET_WORKOUT_LIST_SUCCESS = 'GET_WORKOUT_LIST_SUCCESS'
export const GET_WORKOUT_LIST_FAILURE = 'GET_WORKOUT_LIST_FAILURE'
export const ADD_WORKOUT_SUCCESS = 'ADD_WORKOUT_SUCCESS'
export const ADD_WORKOUT_FAILURE = 'ADD_WORKOUT_FAILURE'
